const stock_options = [
    { value: 'AAPL', label: 'Apple.' },
    { value: 'ABNB', label: 'Airbnb' },
    { value: 'ADBE', label: 'Adobe' },
    { value: 'ADI', label: 'Analog Devices' },
    { value: 'ADP', label: 'Automatic Data Processing' },
    { value: 'ADSK', label: 'Autodesk' },
    { value: 'AEP', label: 'American Electric Power Company' },
    { value: 'ALGN', label: 'Align Technology' },
    { value: 'AMAT', label: 'Applied Materials' },
    { value: 'AMD', label: 'Advanced Micro Devices' },
    { value: 'AMGN', label: 'Amgen' },
    { value: 'AMZN', label: 'Amazon.com' },
    { value: 'ANSS', label: 'ANSYS' },
    { value: 'ASML', label: 'ASML Holding N.V.' }, 
    { value: 'ATVI', label: 'Activision Blizzard' }, 
    { value: 'AVGO', label: 'Broadcom' },
    { value: 'BIDU', label: 'Baidu' },
    { value: 'BIIB', label: 'Biogen' },
    { value: 'BKNG', label: 'Booking Holdings' },
    { value: 'CDNS', label: 'Cadence Design Systems' },
    { value: 'CHTR', label: 'Charter Communications' },
    { value: 'CMCSA', label: 'Comcast Corporation' },
    { value: 'COST', label: 'Costco Wholesale Corporation' },
    { value: 'CPRT', label: 'Copart' },
    { value: 'CRWD', label: 'CrowdStrike Holdings' },
    { value: 'CSCO', label: 'Cisco Systems' },
    { value: 'CSX', label: 'CSX Corporation' },
    { value: 'CTAS', label: 'Cintas Corporation' },
    { value: 'CTSH', label: 'Cognizant Technology Solutions' },
    { value: 'DDOG', label: 'Datadog' },
    { value: 'DLTR', label: 'Dollar Tree' },
    { value: 'DOCU', label: 'DocuSign' },
    { value: 'DXCM', label: 'DexCom' },
    { value: 'EA', label: 'Electronic Arts' },
    { value: 'EBAY', label: 'eBay' },
    { value: 'EXC', label: 'Exelon Corporation' },
    { value: 'FAST', label: 'Fastenal Company' },
    { value: 'FB', label: 'Meta Platforms' },
    { value: 'FISV', label: 'Fiserv' },
    { value: 'FTNT', label: 'Fortinet' },
    { value: 'GILD', label: 'Gilead Sciences' },
    { value: 'GOOG', label: 'Alphabet Class C' },
    { value: 'GOOGL', label: 'Alphabet Class A' },
    { value: 'HON', label: 'Honeywell International' },
    { value: 'IDXX', label: 'IDEXX Laboratories' },
    { value: 'ILMN', label: 'Illumina' },
    { value: 'INTC', label: 'Intel Corporation' },
    { value: 'INTU', label: 'Intuit' },
    { value: 'ISRG', label: 'Intuitive Surgical' },
    { value: 'JD', label: 'JD.com' },
    { value: 'KDP', label: 'Keurig Dr Pepper' },
    { value: 'KHC', label: 'The Kraft Heinz Company' },
    { value: 'KLAC', label: 'KLA Corporation' },
    { value: 'LCID', label: 'Lucid Group' },
    { value: 'LRCX', label: 'Lam Research Corporation' },
    { value: 'LULU', label: 'lululemon athletica' },
    { value: 'MAR', label: 'Marriott International' },
    { value: 'MCHP', label: 'Microchip Technology' },
    { value: 'MDLZ', label: 'Mondelez International' },
    { value: 'MELI', label: 'MercadoLibre' },
    { value: 'MNST', label: 'Monster Beverage Corporation' },
    { value: 'MRNA', label: 'Moderna' },
    { value: 'MRVL', label: 'Marvell Technology' },
    { value: 'MSFT', label: 'Microsoft Corporation' },
    { value: 'MTCH', label: 'Match Group' },
    { value: 'MU', label: 'Micron Technology' },
    { value: 'NFLX', label: 'Netflix' },
    { value: 'NTES', label: 'NetEase' },
    { value: 'NVDA', label: 'NVIDIA' },
    { value: 'NXPI', label: 'NXP Semiconductors' },
    { value: 'OKTA', label: 'Okta' },
    { value: 'ORLY', label: 'O\'Reilly Automotive' },
    { value: 'PANW', label: 'Palo Alto Networks' },
    { value: 'PAYX', label: 'Paychex' },
    { value: 'PCAR', label: 'PACCAR' },
    { value: 'PDD', label: 'Pinduoduo' },
    { value: 'PEP', label: 'PepsiCo' },
    { value: 'PTON', label: 'Peloton Interactive' },
    { value: 'PYPL', label: 'PayPal Holdings' },
    { value: 'QCOM', label: 'QUALCOMM' },
    { value: 'REGN', label: 'Regeneron Pharmaceuticals' },
    { value: 'ROST', label: 'Ross Stores' },
    { value: 'SBUX', label: 'Starbucks' },
    { value: 'SGEN', label: 'Seagen' },
    { value: 'SIRI', label: 'Sirius XM Holdings' },
    { value: 'SNPS', label: 'Synopsys' },
    { value: 'SPLK', label: 'Splunk' },
    { value: 'SWKS', label: 'Skyworks Solutions' },
    { value: 'TEAM', label: 'Atlassian Corporation Plc' },
    { value: 'TMUS', label: 'T-Mobile US' },
    { value: 'TSLA', label: 'Tesla' },
    { value: 'TXN', label: 'Texas Instruments' },
    { value: 'VRSK', label: 'Verisk Analytics' },
    { value: 'VRSN', label: 'VeriSign' },
    { value: 'VRTX', label: 'Vertex Pharmaceuticals' },
    { value: 'WBA', label: 'Walgreens Boots Alliance' },
    { value: 'WDAY', label: 'Workday' },
    { value: 'XEL', label: 'Xcel Energy' },
    { value: 'XLNX', label: 'Xilinx' },
    { value: 'ZM', label: 'Zoom Video Communications' },
    { value: 'ZS', label: 'Zscaler' }
];

export default stock_options;
